######## New MorphoDynamX session v2.0 r2-1582: 2024-10-24 10:16:53

Process.Tools__System__Load_View('')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-1582: 2024-10-24 12:01:11
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Model__Symplastic_Connections__Figure_simulations('3b', 'data/', 'output/', 'parameters.txt')
Process.Model__Symplastic_Connections__Figure_simulations('3b', 'Meshes/Onion/', 'data/', 'parameters.txt')
Process.Model__Symplastic_Connections__Figure_simulations('3b', 'Meshes/Onion/1_2/', 'data/', 'parameters.txt')
Process.Model__Symplastic_Connections__Figure_simulations('3b', 'Meshes/Onion/1_2/', 'data/', 'parameters.txt')
Process.Model__Symplastic_Connections__Figure_simulations('3b', 'Meshes/Onion/1_2/', '', 'parameters.txt')
Process.Model__Symplastic_Connections__Figure_simulations('3b', 'Meshes/Onion/1_2/', 'output/', 'parameters.txt')
Process.Model__Symplastic_Connections__Figure_simulations('S2a', 'Meshes/Onion/1_2/', 'output/', 'parameters.txt')
Process.Model__Symplastic_Connections__Figure_simulations('S2b', 'Meshes/Onion/1_2/', 'output/', 'parameters.txt')
Process.Model__Symplastic_Connections__Figure_simulations('3b', 'Meshes/Onion/1_2/', 'output/', 'parameters.txt')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-1582: 2024-10-24 16:19:56
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Tools__System__Save_View('/usr/users/JIC_a5/tomkinsm/symplastic-guard-cell-connections/Software/Onion/FemMembranes.mdxv')
Process.Model__Symplastic_Connections__Figure_simulations('3b', '../../Meshes/Onion/1_2/', 'output/', 'parameters.txt')
Process.Tools__System__Load_View('/home/tomkinsm/symplastic-guard-cell-connections/Software/Onion/FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-1582: 2024-11-25 09:37:22
Process.Tools__System__Load_View('/home/tomkinsm/symplastic-guard-cell-connections/Software/Onion/FemMembranes.mdxv')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-1582: 2024-11-25 09:38:04
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '40', '400', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__32_Set_Ansio_Dir_From_Lines('Linear Triangle', 'Triangle Element', 'E2', 'Orthogonal', '1e-6', 'Polygon')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Volumes')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__CCF__91_Set_Face_Pressure_From_Volumes('', '', 'Fem Pressure', 'Triangle Element', 'Signal Name')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__CCF__90_Set_3D_Cell_Pressure('', '', '0.5', 'Signal Name')
Process.Model__CCF__91_Set_Face_Pressure_From_Volumes('', '', 'Fem Pressure', 'Triangle Element', 'Signal Name')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Load_Selection('', 'No', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 1 1', 'Fem Dirichlet')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Model__CCF__90_Set_3D_Cell_Pressure('', '', '4.5', 'Signal Name')
Process.Model__CCF__91_Set_Face_Pressure_From_Volumes('', '', 'Fem Pressure', 'Triangle Element', 'Signal Name')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-1582: 2024-11-25 10:35:54
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-1582: 2024-11-25 10:36:36
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-1582: 2024-11-25 10:38:33
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-1582: 2024-11-25 10:39:15
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-1582: 2024-11-25 10:40:14
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-1582: 2024-11-25 10:43:22
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-1582: 2024-11-25 10:53:36
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Model__Symplastic_Connections__Figure_simulations('3c', '../../Meshes/Onion/1_2/', 'output/', 'parameters.txt', '0.9')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-1582: 2024-11-25 12:17:48
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Model__Symplastic_Connections__Figure_simulations('3b', '../../Meshes/Onion/1_2/', 'output/', 'parameters.txt', '0.9')
Process.Model__Symplastic_Connections__Figure_simulations('3c', '../../Meshes/Onion/1_2/', 'output/', 'parameters.txt', '0.9')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-1582: 2024-11-25 15:45:40
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-1582: 2024-12-02 10:41:31
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Model__Symplastic_Connections__Figure_simulations('3b', '../../Meshes/Onion/1_2/', 'output/', 'parameters.txt', '0.9')
Process.Model__Symplastic_Connections__Figure_simulations('3c', '../../Meshes/Onion/1_2/', 'output/', 'parameters.txt', '0.9')
Process.Mesh__Attributes__Save_Attributes_to_CSV('', '')
Process.Mesh__Attributes__Manage_Attributes('')
Process.Mesh__Attributes__Manage_Attributes('')
Process.Mesh__Attributes__Save_Attributes_to_CSV('', '')
Process.Mesh__Attributes__Clean_Index_Attributes('', 'No', 'Yes', 'Yes', 'Yes', 'Yes')
Process.Mesh__Attributes__Manage_Attributes('')
Process.Mesh__Axis__Save_Axis_Attribute('', '', '', '')
Process.Mesh__Axis__Save_Axis_Attribute('', '', 'stress', 'data')
Process.Mesh__Axis__Save_Axis_Attribute('', '', 'Stress', 'data')
Process.Mesh__Axis__Save_Axis_Attribute('', '', 'Stress', 'data')
Process.Mesh__Axis__Save_Axis_Attribute('', '', 'Stress', 'data')
Process.Model__CCF__998_Inflate_Outputs_Equal_Pressure('parameters.txt', '5.0', '5.0')
Process.Model__CCF__998_Inflate_Outputs_Equal_Pressure('parameters.txt', '5.0', '5.0')
Process.Mesh__System__Reset('')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__System__Open('', '', 'No', 'No')
Process.Mesh__Selection__Action__Select_All('Faces')
Process.Model__CCF__03_Reference_Configuration('', '', 'Linear Triangle', 'Triangle Element', 'False', '1.0')
Process.Model__CCF__04_StressStrain('Stress', 'Strain', '', '', '', '', '', '', '', '', 'Von Mises Stress', 'Stress', 'Strain', '1.0', 'No', '', '1', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Set_Material_Properties('', '', '40', '400', '0.3', '1', 'Faces', 'TransIso Material')
Process.Model__CCF__32_Set_Ansio_Dir_From_Lines('Linear Triangle', 'Triangle Element', 'E2', 'Orthogonal', '1e-6', 'Polygon')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Load_Selection('', 'No', 'No')
Process.Model__CCF__09_Set_Dirichlet('', '', '1 1 1', 'Fem Dirichlet')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Mesh__Selection__Action__Select_All('Volumes')
Process.Model__CCF__90_Set_3D_Cell_Pressure('', '', '5', 'Signal Name')
Process.Model__CCF__91_Set_Face_Pressure_From_Volumes('', '', 'Fem Pressure', 'Triangle Element', 'Signal Name')
Process.Mesh__Selection__Action__Clear_Selection('All')
Process.Model__CCF__01_FEM_Membranes('', '', '10', '.1', '.0001', '10', '1.1', '0.7', '0.1', '10', '0.1', 'Backward Euler', 'Preconditioned Conjugate Gradient', '50', '1e-10', 'Yes', '10e-5', 'Model/CCF/04 StressStrain', '', 'Model/CCF/02 Triangle Derivs', 'Model/CCF/08 Pressure Derivs', 'Model/CCF/10 Dirichlet Derivs')
Process.Mesh__Axis__Save_Axis_Attribute('', '', 'Stress', 'stress50_50')
Process.Model__Symplastic_Connections__Figure_simulations('3c', '../../Meshes/Onion/1_2/', 'output/', 'parameters.txt', '0.7')
Process.Mesh__Axis__Save_Axis_Attribute('', '', 'Stress', 'stress70_30')
Process.Model__Symplastic_Connections__Figure_simulations('3c', '../../Meshes/Onion/1_2/', 'output/', 'parameters.txt', '0.5')
Process.Mesh__Axis__Save_Axis_Attribute('', '', 'Stress', 'stress50_50')
